# Homework 1 - Fundamentos de Machine Learning

## Solución a las preguntas del homework

En esta notebook se encuentran las respuestas a las preguntas del homework 1 del Machine Learning Zoomcamp 2025.

### Datos utilizados
Para este homework utilizaremos el dataset de automóviles que contiene información sobre diferentes características de vehículos.


In [1]:
# Importar librerías necesarias
import pandas as pd
import numpy as np

print("Librerías importadas correctamente")

Librerías importadas correctamente


In [4]:
!mkdir data

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-27 16:45:33--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.09s   

2025-09-27 16:45:33 (8.97 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [6]:
!mv car_fuel_efficiency.csv ./data/

In [9]:
# Cargar los datos
df_car = pd.read_csv('data/car_fuel_efficiency.csv')

print("Datos cargados correctamente")

Datos cargados correctamente


## Q1. Pandas version

**Pregunta:** ¿Cuál es la versión de pandas que estás usando?

**Respuesta:**


In [3]:
print(f"Versión de pandas: {pd.__version__}")

Versión de pandas: 2.3.2


'2.3.2'

## Q2. Records count

**Pregunta:** ¿Cuántos registros hay en el conjunto de datos?

**Respuesta:**


In [10]:
print(f"Número de registros: {len(df_car)}")

Número de registros: 9704


In [11]:
print(f"Dimension del dataset: {df_car.shape}")

Dimension del dataset: (9704, 11)


## Q3. Fuel types

**Pregunta:** ¿Cuáles son los tipos de combustible únicos en el dataset?

**Respuesta:**


In [13]:
df_car.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [14]:
df_car.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [17]:
tip_fuel = df_car['fuel_type'].unique()

In [19]:
print(f"Tipos de combustible únicos: {tip_fuel}")
print(f"Número de tipos únicos: {len(tip_fuel)}")

Tipos de combustible únicos: ['Gasoline' 'Diesel']
Número de tipos únicos: 2


In [22]:
df_car['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

## Q4. Missing values

**Pregunta:** ¿Cuántas columnas del conjunto de datos tienen valores faltantes?

**Respuesta:**


In [24]:
df_car.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [31]:
df_car.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [34]:
df_null = df_car.isnull().sum()

print("Valores faltantes por columna:")
print(df_null[df_null > 0])

Valores faltantes por columna:
num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64


In [35]:
total_missing = int(df_car.isnull().sum().sum())
print(f"\nTotal de valores faltantes: {total_missing}")


Total de valores faltantes: 2622


## Q5. Max fuel efficiency

**Pregunta:** ¿Cuál es la máxima eficiencia de combustible en el dataset?

**Respuesta:**


In [36]:
df_car.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [37]:
df_car['origin'].value_counts()

origin
Europe    3254
Asia      3247
USA       3203
Name: count, dtype: int64

In [50]:
df_car[df_car['origin'] == 'Asia'].head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [51]:
df_car_asia = df_car[df_car['origin'] == 'Asia']
df_car_asia.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          3247.000000    3099.000000  3013.000000     3247.000000   
mean            200.052356       4.010326   150.303352     3006.292228   
std              49.287252       1.971199    30.257169      502.434626   
min              30.000000       0.000000    40.000000     1223.298226   
25%             170.000000       3.000000   130.000000     2665.518985   
50%             200.000000       4.000000   150.000000     2988.585737   
75%             230.000000       5.000000   171.000000     3345.355571   
max             370.000000      11.000000   245.000000     4661.144932   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   2933.000000  3247.000000  3072.000000          3247.000000  
mean      15.036754  2011.489375    -0.001628            14.973830  
std        2.488340     6.704607     1.051428             2.578345  
min        6.400000  2000.000000    -4.000000             6.886245  
25%       13.300000  2006.000000    -1.000000            13.252010  
50%       15.100000  2012.000000     0.000000            15.034670  
75%       16.700000  2017.000000     1.000000            16.726318  
max       22.700000  2023.000000     4.000000            23.759123

In [52]:
max_fuel_efficiency = df_car_asia['fuel_efficiency_mpg'].max()
print(f"Máxima eficiencia de combustible: {max_fuel_efficiency:.3f}")

Máxima eficiencia de combustible: 23.759


## Q6. Median value of horsepower

**Pregunta:** ¿Cuál es el valor mediano de caballos de fuerza?

**Respuesta:**


In [61]:
median_hp = df_car['horsepower'].median()
median_hp

np.float64(149.0)

In [62]:
df_car['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [63]:
df_car_fill_horsepower = df_car.fillna({'horsepower':152})
df_car_fill_horsepower

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0       152.0     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [65]:
fill_median_hp = df_car_fill_horsepower['horsepower'].median()
fill_median_hp

np.float64(152.0)

In [68]:
print(f"Valor mediano de caballos de fuerza cambio luego del fillna: {median_hp!=fill_median_hp}, antes {median_hp} vs ahora {fill_median_hp}")

Valor mediano de caballos de fuerza cambio luego del fillna: True, antes 149.0 vs ahora 152.0


## Q7. Sum of weights

**Pregunta:** ¿Cuál es la suma de todos los pesos en el dataset?

**Respuesta:**


In [113]:
df_car_asia = df_car[df_car['origin'] == 'Asia']
df_car_asia.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [115]:
df_weight_year = df_car_asia[['vehicle_weight', 'model_year']]

In [116]:
df_weight_year.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [117]:
X = df_weight_year.head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [118]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [119]:
XTX_inversa = np.linalg.inv(XTX)
XTX_inversa

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [120]:
list_y = [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array(list_y)
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [121]:
w_1 = XTX_inversa.dot(X.T) 
w = w_1.dot(y)
w

array([0.01386421, 0.5049067 ])

In [122]:
w = XTX_inversa @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [123]:
print(f"Suma total de pesos: {sum(w)}")

Suma total de pesos: 0.5187709081074016
